# Generated by Django 5.0 on 2024-02-07 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staticmodel',
            name='staticType',
            field=models.CharField(choices=[('HS', 'Home Slider'), ('ML', 'Menu Link'), ('OT', 'Other')], default='OT', max_length=2),
        ),
    ]
