# Generated by Django 5.0 on 2024-02-07 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0002_staticmodel_statictype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmodel',
            name='image',
            field=models.ImageField(upload_to='essential_events_main/static/images/staticModel/'),
        ),
    ]
