# Generated by Django 5.0 on 2024-02-08 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0003_alter_staticmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmodel',
            name='staticType',
            field=models.CharField(choices=[('HS', 'Home Slider'), ('ML', 'Menu Link'), ('OT', 'Other'), ('HH', 'Home Page Hero Details')], default='OT', max_length=2),
        ),
    ]
