# Generated by Django 5.0 on 2024-02-08 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0005_alter_staticmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmodel',
            name='image',
            field=models.ImageField(upload_to='staticModel/'),
        ),
    ]
