# Generated by Django 5.0 on 2024-02-08 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0006_alter_staticmodel_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmodel',
            name='description',
            field=models.CharField(max_length=400),
        ),
    ]
