# Generated by Django 5.0 on 2024-02-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0007_alter_staticmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='menuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayName', models.CharField(max_length=20)),
                ('slug', models.SlugField(blank=-1, default='')),
            ],
        ),
    ]
