# Generated by Django 5.0 on 2024-02-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0008_menuitems'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staticmodel',
            name='description',
            field=models.TextField(max_length=400),
        ),
    ]
