# Generated by Django 5.0 on 2024-02-20 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0009_alter_staticmodel_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='actsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('category', models.CharField(max_length=2)),
                ('main_image', models.ImageField(upload_to='actsModel/')),
                ('slug', models.SlugField(blank=-1, default='')),
            ],
        ),
    ]
