# Generated by Django 5.0 on 2024-02-20 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essential_events_main', '0010_actsmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='actImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('altDescription', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='actsModel/')),
                ('slug', models.SlugField(blank=-1, default='')),
                ('actName', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='essential_events_main.actsmodel')),
            ],
        ),
    ]
